#!/bin/sh
set -e

cat >/output/postgresql.conf <<EOF
POSTGRES_HOST=$1
POSTGRES_PORT=$3
POSTGRES_USER=$4
POSTGRES_DB=$5
POSTGRES_PASSWORD=$6
PDNS_POSTGRES_HOST=$1
PDNS_POSTGRES_PORT=$3
PDNS_POSTGRES_USER=$4
PDNS_POSTGRES_DB=pdns
PDNS_POSTGRES_PASSWORD=$6
EOF
